#!/usr/bin/env bash

INIT_FILE='tmp_files.dat'
TRIM_FILE='tmp_files_2.dat'
NO_LEAD_FILE='files.dat'
OUTPUT_FILE='output.dat'

find_files ()
{
    find $PWD/src/ -name "*.cpp" > "$INIT_FILE"
    find $PWD/include/ -name "*.h" >> "$INIT_FILE"
}

clean ()
{
    rm "$INIT_FILE"
    rm "$NO_LEAD_FILE"
}

find_files
grep . "$INIT_FILE" --no-messages > "$NO_LEAD_FILE"

lineReader "$NO_LEAD_FILE" > "$OUTPUT_FILE" 2>&1
clean
